image:
  repository: nvcr.io/nvidia/pytorch

service:
  port: 
    port: 8888

strategy:
  type: Recreate

resources:
  limits:
    # One nvidia.com/gpu as standard (or 8 total)
    nvidia.com/gpu: 1
  requests: # What we need to be scheduled
    memory: "16Gi"
    cpu: "4"

# We want to save data over time
persistence:
  data:
    accessMode: "ReadWriteOnce"	
    enabled: true
    size: 100Gi
    emptyDir: false
    mountPath: /workspace
  shm:
    enabled: true
    emptyDir:
      enabled: true
      medium: "Memory"
    mountPath: /dev/shm    

# initContainer to try to copy what's in the image by default in /workspace to the storage if it's not there
initContainers:
- name: copy-workspace
  image: nvcr.io/nvidia/pytorch:23.12-py3
  command: [ 'sh', '-c', 'if [ ! -f /data/README.md ]; then cp -a /workspace/* /data/ ; fi; ls -l /data' ]
  volumeMounts:
  - mountPath: /data
    name: data
# Set command to wait in the background
command: ["/usr/local/bin/jupyter-notebook"]

# Disable service links env Variables, the code is not working if you do a release named jupyter
enableServiceLinks: false


# Disable the liveness probe
probes:
  liveness:
    enabled: false
